package com.demo.service.base;

import java.util.List;

/**
 * Created by Administrator on 2017-1-3.
 */
public interface BaseService<R>  {

    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_demo
     *
     * @mbg.generated Mon Sep 28 15:16:02 CST 2020
     */
    int insert(R record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_demo
     *
     * @mbg.generated Mon Sep 28 15:16:02 CST 2020
     */
    int insertSelective(R record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_demo
     *
     * @mbg.generated Mon Sep 28 15:16:02 CST 2020
     */
    R selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_demo
     *
     * @mbg.generated Mon Sep 28 15:16:02 CST 2020
     */
    int updateByPrimaryKeySelective(R record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_demo
     *
     * @mbg.generated Mon Sep 28 15:16:02 CST 2020
     */
    int updateByPrimaryKey(R record);
}
