spring:
  datasource:
    url: jdbc:mysql://192.168.0.10:3306/db3?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 0
    host: 192.168.0.10
    port: 6379
mybatis:
  mapper-locations: classpath*:com/demo/mapper/**/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: classpath:com.demo.entity.*
logging:
  config: classpath:log4j2.xml
server:
  servlet:
    context-path: /spring-boot-demo