#dev环境
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://192.168.0.1:3306/local?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  http:
    multipart:
      max-file-size: 3MB
  redis:
    database: 0
    host: 101.37.37.113
    port: 6379
    password: happyhome123ll3KK45,AA?
    timeout: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
server:
  context-path: /demo
  port: 8080
mybatis:
  mapper-locations: classpath*:com/demo/mapper/**/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: classpath:com.demo.entity.*
logging:
  config: classpath:log4j2.xml

#uat环境
---
spring:
  profiles: uat
  datasource:
    url: jdbc:mysql://192.168.0.2:3306/uat?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  http:
    multipart:
      max-file-size: 3MB
  redis:
    database: 0
    host: 101.37.37.113
    port: 6379
    password: happyhome123ll3KK45,AA?
    timeout: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
server:
  context-path: /demo
  port: 8080
mybatis:
  mapper-locations: classpath*:com/demo/mapper/**/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: classpath:com.demo.entity.*
logging:
  config: classpath:log4j2.xml

#prod环境
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://192.168.0.3:3306/prod?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  http:
    multipart:
      max-file-size: 3MB
  redis:
    database: 0
    host: 101.37.37.113
    port: 6379
    password: happyhome123ll3KK45,AA?
    timeout: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
server:
  context-path: /demo
  port: 8080
mybatis:
  mapper-locations: classpath*:com/demo/mapper/**/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: classpath:com.demo.entity.*
logging:
  config: classpath:log4j2.xml