package com.demo.dao.base;

import com.demo.entity.demo.Demo;

public interface BaseDao<T> {

    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_demo
     *
     * @mbg.generated Mon Sep 28 15:16:02 CST 2020
     */
    int insert(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_demo
     *
     * @mbg.generated Mon Sep 28 15:16:02 CST 2020
     */
    int insertSelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_demo
     *
     * @mbg.generated Mon Sep 28 15:16:02 CST 2020
     */
    T selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_demo
     *
     * @mbg.generated Mon Sep 28 15:16:02 CST 2020
     */
    int updateByPrimaryKeySelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_demo
     *
     * @mbg.generated Mon Sep 28 15:16:02 CST 2020
     */
    int updateByPrimaryKey(T record);
}
