package com.demo.entity.box;

import java.util.Date;

public class Box {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_box.id
     *
     * @mbg.generated Mon Oct 12 15:38:51 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_box.box_key
     *
     * @mbg.generated Mon Oct 12 15:38:51 CST 2020
     */
    private String boxKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_box.box_name
     *
     * @mbg.generated Mon Oct 12 15:38:51 CST 2020
     */
    private String boxName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_box.create_date
     *
     * @mbg.generated Mon Oct 12 15:38:51 CST 2020
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_box.update_time
     *
     * @mbg.generated Mon Oct 12 15:38:51 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_box.id
     *
     * @return the value of tb_box.id
     *
     * @mbg.generated Mon Oct 12 15:38:51 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_box.id
     *
     * @param id the value for tb_box.id
     *
     * @mbg.generated Mon Oct 12 15:38:51 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_box.box_key
     *
     * @return the value of tb_box.box_key
     *
     * @mbg.generated Mon Oct 12 15:38:51 CST 2020
     */
    public String getBoxKey() {
        return boxKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_box.box_key
     *
     * @param boxKey the value for tb_box.box_key
     *
     * @mbg.generated Mon Oct 12 15:38:51 CST 2020
     */
    public void setBoxKey(String boxKey) {
        this.boxKey = boxKey == null ? null : boxKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_box.box_name
     *
     * @return the value of tb_box.box_name
     *
     * @mbg.generated Mon Oct 12 15:38:51 CST 2020
     */
    public String getBoxName() {
        return boxName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_box.box_name
     *
     * @param boxName the value for tb_box.box_name
     *
     * @mbg.generated Mon Oct 12 15:38:51 CST 2020
     */
    public void setBoxName(String boxName) {
        this.boxName = boxName == null ? null : boxName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_box.create_date
     *
     * @return the value of tb_box.create_date
     *
     * @mbg.generated Mon Oct 12 15:38:51 CST 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_box.create_date
     *
     * @param createDate the value for tb_box.create_date
     *
     * @mbg.generated Mon Oct 12 15:38:51 CST 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_box.update_time
     *
     * @return the value of tb_box.update_time
     *
     * @mbg.generated Mon Oct 12 15:38:51 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_box.update_time
     *
     * @param updateTime the value for tb_box.update_time
     *
     * @mbg.generated Mon Oct 12 15:38:51 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}