package com.demo.dao.demo;

import com.demo.dao.base.BaseDao;
import com.demo.entity.demo.Demo;

public interface DemoDao extends BaseDao<Demo> {
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table tb_demo
//     *
//     * @mbg.generated Mon Sep 28 15:16:02 CST 2020
//     */
//    int deleteByPrimaryKey(Integer id);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table tb_demo
//     *
//     * @mbg.generated Mon Sep 28 15:16:02 CST 2020
//     */
//    int insert(Demo record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table tb_demo
//     *
//     * @mbg.generated Mon Sep 28 15:16:02 CST 2020
//     */
//    int insertSelective(Demo record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table tb_demo
//     *
//     * @mbg.generated Mon Sep 28 15:16:02 CST 2020
//     */
//    Demo selectByPrimaryKey(Integer id);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table tb_demo
//     *
//     * @mbg.generated Mon Sep 28 15:16:02 CST 2020
//     */
//    int updateByPrimaryKeySelective(Demo record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table tb_demo
//     *
//     * @mbg.generated Mon Sep 28 15:16:02 CST 2020
//     */
//    int updateByPrimaryKey(Demo record);
}