package com.demo.entity.demo;

import java.time.LocalDateTime;
import java.util.Date;

public class Demo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_demo.id
     *
     * @mbg.generated Mon Sep 28 15:44:14 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_demo.demo_key
     *
     * @mbg.generated Mon Sep 28 15:44:14 CST 2020
     */
    private String demoKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_demo.demo_name
     *
     * @mbg.generated Mon Sep 28 15:44:14 CST 2020
     */
    private String demoName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_demo.create_date
     *
     * @mbg.generated Mon Sep 28 15:44:14 CST 2020
     */
    private LocalDateTime createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_demo.update_time
     *
     * @mbg.generated Mon Sep 28 15:44:14 CST 2020
     */
    private LocalDateTime updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_demo.id
     *
     * @return the value of tb_demo.id
     *
     * @mbg.generated Mon Sep 28 15:44:14 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_demo.id
     *
     * @param id the value for tb_demo.id
     *
     * @mbg.generated Mon Sep 28 15:44:14 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_demo.demo_key
     *
     * @return the value of tb_demo.demo_key
     *
     * @mbg.generated Mon Sep 28 15:44:14 CST 2020
     */
    public String getDemoKey() {
        return demoKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_demo.demo_key
     *
     * @param demoKey the value for tb_demo.demo_key
     *
     * @mbg.generated Mon Sep 28 15:44:14 CST 2020
     */
    public void setDemoKey(String demoKey) {
        this.demoKey = demoKey == null ? null : demoKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_demo.demo_name
     *
     * @return the value of tb_demo.demo_name
     *
     * @mbg.generated Mon Sep 28 15:44:14 CST 2020
     */
    public String getDemoName() {
        return demoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_demo.demo_name
     *
     * @param demoName the value for tb_demo.demo_name
     *
     * @mbg.generated Mon Sep 28 15:44:14 CST 2020
     */
    public void setDemoName(String demoName) {
        this.demoName = demoName == null ? null : demoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_demo.create_date
     *
     * @return the value of tb_demo.create_date
     *
     * @mbg.generated Mon Sep 28 15:44:14 CST 2020
     */
    public LocalDateTime getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_demo.create_date
     *
     * @param createDate the value for tb_demo.create_date
     *
     * @mbg.generated Mon Sep 28 15:44:14 CST 2020
     */
    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_demo.update_time
     *
     * @return the value of tb_demo.update_time
     *
     * @mbg.generated Mon Sep 28 15:44:14 CST 2020
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_demo.update_time
     *
     * @param updateTime the value for tb_demo.update_time
     *
     * @mbg.generated Mon Sep 28 15:44:14 CST 2020
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }
}